# Generated by Django 5.2.3 on 2025-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
